// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlalcqptjcegvvuwacfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsYWxjcXB0amNlZ3Z2dXdhY2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMjcyNzAsImV4cCI6MjA2OTYwMzI3MH0.nBAMNPlGRxGssSmzND3ZKpE3Iv-UZ4RBhHn5pO67F0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});